In [9]:
import torch
import numpy as np

In [2]:
####### set_default_dtype##########
torch.tensor([1.2,3]).dtype

torch.float32

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.tensor([1.2,4]).dtype ##sirve entonces para cambiar la precisión a doble para todos los tensores definidos de ahí en adelante.

torch.float64

In [8]:
######## numel ######
#Devuelve el número total de elementos en todas las dimensiones del tensor

a = torch.randn(1,2,3,4,5)
a.numel()

120

In [19]:
##### as_tensor #### convierte los datos en un tensor

a = np.array([[1,2,3],[4,5,6]])
b = torch.as_tensor(a)
b[0][0] = -2
print(a,b) ### cambia el tensor, pero también el numpy array

c = [1,2,3,5]
d = torch.as_tensor(c)
d[0] = 3
print(c,d) ### si el dato inicial no era un numpy array entonces no se cambia el dato inicial

[[-2  2  3]
 [ 4  5  6]] tensor([[-2,  2,  3],
        [ 4,  5,  6]])
[1, 2, 3, 5] tensor([3, 2, 3, 5])


In [23]:
#### from_numpy ##### convierte un numpy array en un tensor

a = np.array([[1,2,3],[4,5,6]])
t_a = torch.from_numpy(a)  ### comparten memoria, la modificación de uno altera al otro
a[0][0] = 4
t_a[1][1] = 9
print(a,t_a)


[[4 2 3]
 [4 9 6]] tensor([[4, 2, 3],
        [4, 9, 6]])


In [24]:
### zeros ### devuelve un tensor de ceros
torch.zeros((2,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#### ones #### devuelve tensor de unos
torch.ones((4,6))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])